migrated to the new slimer header

diff --git a/bin/curate-pkg b/bin/curate-pkg
--- a/bin/curate-pkg
+++ b/bin/curate-pkg
@@ -3,16 +3,12 @@
 # Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
 # Licensed under the MIT License
 
-# Fail script if any command fails.
-set -eu
+# Get script path and append it to PATH so other scripts are callable.
+SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
+PATH="${PATH}:${SCRIPT_PATH}"
 
-# Print usage function.
-function printUsage() {
-printf "\
-Usage: $(basename "${0}") [options]
-Options:
-  [-d|--debug]                       Enable debug.
-  [-h|--help]                        Display this help.
+# Header
+ARGUMENTS="\
   [-a|--auto]                        Cool continuous curation
   [-v|--verbose]                     Verbose output
   [-i|--install \$package]            Installs a single package.
@@ -21,99 +17,42 @@ Options:
   [-r|--add-repository \$repository]  Adds a single repository.
   [-s|--add-source \$source]          Adds a single source.
   [-u|--upgrade \$package]            Upgrades a single package.
+  \$package_manager                   Run only for this specific package manager.
 "
-}
-
-# Traps
-# shellcheck disable=SC2154
-trap 'return_code=${?}; trap - EXIT; echo EXIT ${return_code}' EXIT
-trap 'return_code=${?}; trap - EXIT; echo HUP ${return_code}' HUP
-trap 'return_code=${?}; trap - EXIT; echo INT ${return_code}' INT
-trap 'return_code=${?}; trap - EXIT; echo QUIT ${return_code}' QUIT
-trap 'return_code=${?}; trap - EXIT; echo PIPE ${return_code}' PIPE
-trap 'return_code=${?}; trap - EXIT; echo TERM ${return_code}' TERM
-trap 'trap - EXIT; echo QUIT' QUIT
-
-# Get script path and append it to PATH so other scripts are callable.
-script_path="$(dirname "${0}")"
-PATH="${PATH}:${script_path}"
+. "${SCRIPT_PATH}/../share/curate-pkg/header"
+. "${SCRIPT_PATH}/../share/curate-pkg/spinner"
 
 # Parse arguments.
 additional=
 auto=false
-while [[ ${#} -ge 1 ]]; do
-  # Debug mode
-  if [[ "${1}" == "-d" || "${1}" == "--debug" ]]; then
-    shift
-    set -x
-    additional+=" -d"
-    continue
-  fi
-  # Help: display usage
-  if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
-    shift
-    printUsage
-    exit 0
-  fi
-  # auto
-  if [[ "${1}" == "-a" || "${1}" == "--auto" ]]; then
-    shift
-    auto=true
-    continue
-  fi
-  # install
-  if [[ "${1}" == "-i" || "${1}" == "--install" ]]; then
-    shift
-    additional+=" -i ${1}"
-    shift
-    continue
-  fi
-  # add-key
-  if [[ "${1}" == "-k" || "${1}" == "--add-key" ]]; then
-    shift
-    additional+=" -k ${1}"
-    shift
-    continue
-  fi
-  # purge
-  if [[ "${1}" == "-p" || "${1}" == "--purge" || "${1}" == "--remove" ]]; then
-    shift
-    additional+=" -p ${1}"
-    shift
-    continue
-  fi
-  # add-repository
-  if [[ "${1}" == "-r" || "${1}" == "--add-repository" ]]; then
-    shift
-    additional+=" -r ${1}"
-    shift
-    continue
-  fi
-  # add-source
-  if [[ "${1}" == "-s" || "${1}" == "--add-source" ]]; then
-    shift
-    additional+=" -s ${1}"
-    shift
-    continue
-  fi
-  # update
-  if [[ "${1}" == "-u" || "${1}" == "--upgrade" ]]; then
-    shift
-    additional+=" -u ${1}"
-    shift
-    continue
-  fi
-  # Verbose output
-  if [[ "${1}" == "-v" || "${1}" == "--verbose" ]]; then
-    shift
-    additional+=" -v"
-    continue
-  fi
-  # Unrecognized argument.
-  printf "\e[1m\e[31mERROR: Unrecognized argument %s.\e[0m\e[0m\n" "${1}" >&2
-  printUsage
-  exit 1
+while (( ${#} > 0 )); do
+  case "${1}" in
+  # [-a|--auto]                        Cool continuous curation
+  '-a');& '--auto') auto=true;;
+  # [-i|--install \$package]            Installs a single package.
+  '-i');& '--install');&
+  # [-k|--add-key \$key]                Adds a single key.
+  '-k');& '--add-key');&
+  # [-p|--purge|--remove \$package]     Removes a single package.
+  '-p');& '--purge');& '--remove');&
+  # [-r|--add-repository \$repository]  Adds a single repository.
+  '-r');& '--add-repository');&
+  # [-s|--add-source \$source]          Adds a single source.
+  '-s');& '--add-source');&
+  # [-u|--upgrade \$package]            Upgrades a single package.
+  '-u');& '--upgrade')
+    additional+=" ${1} ${2}" && shift;;
+  # [-v|--verbose]                     Verbose output
+  '-v');& '--verbose') additional+=" ${1}";;
+  *)
+    # \$package_manager                   Run only for this specific package manager.
+    [[ -z "${explicit_package_manager}" ]] && explicit_package_manager="${1}" && shift && continue
+    # Unrecognized argument
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1;;
+  esac; shift
 done
+
+#------------------------------------------------------------------------------#
 
 package_managers=$(cat <<EOF
 apt
@@ -135,25 +74,12 @@ yaourt
 EOF
 )
 
-found=false
-for package_manager in ${package_managers}; do
-  if command -v ${package_manager} 1> /dev/null; then
-    found=true
-    break
-  fi
-done
-
-if ! ${found}; then
-  printf "Warning: your package manager is not supported. Send the following output to the developer:\n%s\n" "$(lsb_release -a 2> /dev/null)" >&2
-  exit 2
-fi
-
-# shellcheck disable=SC2068
 while true; do
   for package_manager in ${package_managers} ${optional_package_managers}; do
-    if ! command -v ${package_manager} 1> /dev/null; then
+    if ! command -v ${package_manager} 1> /dev/null || [[ ! -z "${explicit_package_manager}" && "${package_manager}" != "${explicit_package_manager}" ]]; then
       continue
     fi
+    found=true
     if [[ ${package_manager} == "pacaur" ||
           ${package_manager} == "yaourt" ]]; then
       curate-pkg-one ${additional} ${package_manager} || true
@@ -167,3 +93,7 @@ while true; do
   sleep 1h
 done
 
+if ! ${found}; then
+  printf "Warning: your package manager is not supported. Send the following output to the developer:\n%s\n" "$(lsb_release -a 2> /dev/null)" >&2
+  exit 2
+fi
diff --git a/bin/curate-pkg-one b/bin/curate-pkg-one
--- a/bin/curate-pkg-one
+++ b/bin/curate-pkg-one
@@ -3,44 +3,23 @@
 # Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
 # Licensed under the MIT License
 
-# Fail script if any command fails.
-set -eu
+# Get script path and append it to PATH so other scripts are callable.
+SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
+PATH="${PATH}:${SCRIPT_PATH}"
 
-# Print usage function.
-function printUsage() {
-printf "\
-Usage: $(basename "${0}") \${pakage_manager} [options]
-Options:
-  [-d|--debug]                       Enable debug.
-  [-h|--help]                        Display this help.
-  [-v|--verbose]                     Verbose output
+# Header
+ARGUMENTS="\
   [-i|--install \$package]            Installs a single package.
   [-k|--add-key \$key]                Adds a single key.
   [-p|--purge|--remove \$package]     Removes a single package.
   [-r|--add-repository \$repository]  Adds a single repository.
   [-s|--add-source \$source]          Adds a single source.
   [-u|--upgrade \$package]            Upgrades a single package.
+  [-v|--verbose]                     Verbose output
+  \$package_manager                   Run only for this specific package manager.
 "
-}
-
-function cleanup() {
-  ${cleanup_added_sources}
-  spinner_end 0 &> /dev/null
-}
-
-# Traps
-# shellcheck disable=SC2154
-trap 'return_code=${?}; trap - EXIT; cleanup; echo EXIT ${return_code}' EXIT
-trap 'return_code=${?}; trap - EXIT; cleanup; echo HUP ${return_code}' HUP
-trap 'return_code=${?}; trap - EXIT; cleanup; echo INT ${return_code}' INT
-trap 'return_code=${?}; trap - EXIT; cleanup; echo QUIT ${return_code}' QUIT
-trap 'return_code=${?}; trap - EXIT; cleanup; echo PIPE ${return_code}' PIPE
-trap 'return_code=${?}; trap - EXIT; cleanup; echo TERM ${return_code}' TERM
-trap 'trap - EXIT; cleanup; echo QUIT' QUIT
-
-# Get script path and append it to PATH so other scripts are callable.
-script_path="$(dirname "${0}")"
-PATH="${PATH}:${script_path}"
+. "${SCRIPT_PATH}/../share/curate-pkg/header"
+. "${SCRIPT_PATH}/../share/curate-pkg/spinner"
 
 # Parse arguments.
 package_manager=
@@ -52,87 +31,38 @@ install_item=
 purge_item=
 upgrade_item=
 explicit=false
-while [[ ${#} -ge 1 ]]; do
-  # Debug mode
-  if [[ "${1}" == "-d" || "${1}" == "--debug" ]]; then
-    shift
-    set -x
-    continue
-  fi
-  # Help: display usage
-  if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
-    shift
-    printUsage
-    exit 0
-  fi
-  # install
-  if [[ "${1}" == "-i" || "${1}" == "--install" ]]; then
-    shift
-    install_item=${1}
-    explicit=true
-    shift
-    continue
-  fi
-  # add-key
-  if [[ "${1}" == "-k" || "${1}" == "--add-key" ]]; then
-    shift
-    add_key_item=${1}
-    explicit=true
-    shift
-    continue
-  fi
-  # purge
-  if [[ "${1}" == "-p" || "${1}" == "--purge" || "${1}" == "--remove" ]]; then
-    shift
-    purge_item=${1}
-    explicit=true
-    shift
-    continue
-  fi
-  # add-repository
-  if [[ "${1}" == "-r" || "${1}" == "--add-repository" ]]; then
-    shift
-    add_repository_item=${1}
-    explicit=true
-    shift
-    continue
-  fi
-  # add-source
-  if [[ "${1}" == "-s" || "${1}" == "--add-source" ]]; then
-    shift
-    add_source_item=${1}
-    explicit=true
-    shift
-    continue
-  fi
-  # upgrade
-  if [[ "${1}" == "-u" || "${1}" == "--upgrade" ]]; then
-    shift
-    upgrade_item=${1}
-    explicit=true
-    shift
-    continue
-  fi
-  if [[ "${1}" == "-v" || "${1}" == "--verbose" ]]; then
-    shift
-    verbose=
-    continue
-  fi
-  # Package manager
-  if [[ -z "${package_manager}" ]]; then
-    package_manager="${1}"
-    shift
-    continue
-  fi
-  # Unrecognized argument.
-  printf "\e[1m\e[31mERROR: Unrecognized argument %s.\e[0m\e[0m\n" "${1}" >&2
-  printUsage
-  exit 1
+while (( ${#} > 0 )); do
+  case "${1}" in
+  # [-i|--install \$package]            Installs a single package.
+  '-i');& '--install') shift && install_item="${1}" && explicit=true;;
+  # [-k|--add-key \$key]                Adds a single key.
+  '-k');& '--add-key') shift && add_key_item="${1}" && explicit=true;;
+  # [-p|--purge|--remove \$package]     Removes a single package.
+  '-p');& '--purge');& '--remove') shift && purge_item="${1}" && explicit=true;;
+  # [-r|--add-repository \$repository]  Adds a single repository.
+  '-r');& '--add-repository') shift && add_repository_item="${1}" && explicit=true;;
+  # [-s|--add-source \$source]          Adds a single source.
+  '-s');& '--add-source') shift && add_source_item="${1}" && explicit=true;;
+  # [-u|--upgrade \$package]            Upgrades a single package.
+  '-u');& '--upgrade') shift && upgrade_item="${1}" && explicit=true;;
+  # [-v|--verbose]                     Verbose output
+  '-v');& '--verbose') shift && verbose='' && explicit=true;;
+  *)
+    # \$package_manager                   Run only for this specific package manager.
+    [[ -z "${package_manager}" ]] && package_manager="${1}" && shift && continue
+    # Unrecognized argument
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1;;
+  esac; shift
 done
 
-source "${script_path}/../share/curate-pkg/spinner.sh"
+#------------------------------------------------------------------------------#
 
-function header() {
+function cleanup() {
+  ${cleanup_added_sources}
+  spinner_end 0 &> /dev/null
+}
+
+function printHeader() {
   local title="${1}"
   local column_count="$(tput cols)"
   local hash_count=$((column_count - 2 - ${#title}))
@@ -166,35 +96,41 @@ function spinner_end() {
 function install_function() {
   local package="${1}"
   eval "install_ \"${package}\" ${verbose}" || true
+  installed_packages+=("${package}")
 }
 
 function add_key_function() {
   local key="${1}"
   eval "wget -q -O - \"${key}\" | add_key_ - ${verbose}"
+  added_keys+=("${key}")
 }
 
 function purge_function() {
   local package="${1}"
   eval "purge_ \"${package}\" ${verbose}"
+  purged_packages+=("${package}")
 }
 
 function add_repository_function() {
   local repository="${1}"
   eval "add_repository_ \"${repository}\" ${verbose}" || true
+  added_repositories+=("${repository}")
 }
 
 function add_source_function() {
   local source="${1}"
-  eval "add_source_ \"${src}\" ${verbose}"
+  eval "add_source_ \"${source}\" ${verbose}"
+  added_sources+=("${source}")
 }
 
 function upgrade_function() {
   local package="${1}"
   eval "upgrade_ ${package} ${verbose}"
+  upgraded_packages+=("${package}")
 }
 
-header ${package_manager}
-source "${script_path}/../share/curate-pkg/package-managers/${package_manager}.sh"
+printHeader ${package_manager}
+source "${SCRIPT_PATH}/../share/curate-pkg/package-managers/${package_manager}.sh"
 if ! command -v yq 1> /dev/null; then
   ${install} yq
 fi
@@ -224,6 +160,14 @@ if ! ${explicit}; then
   done
 fi
 
+added_keys=()
+added_repositories=()
+added_sources=()
+upgraded_packages=()
+installed_packages=()
+wgot_packages=()
+purged_packages=()
+
 # Do.
 spinner_begin "Adding keys..."
 if ${explicit}; then
@@ -236,6 +180,7 @@ else
   done
 fi
 spinner_end
+(( ${#added_keys[@]} > 0 )) && printf "${GREEN}Added keys: %s${RESET}\n" "${added_keys[@]}"
 
 spinner_begin "Adding repositories..."
 if ! ${explicit}; then
@@ -248,6 +193,7 @@ else
   done
 fi
 spinner_end
+(( ${#added_repositories[@]} > 0 )) && printf "${GREEN}Added repositories: %s${RESET}\n" "${added_repositories[@]}"
 
 spinner_begin "Adding sources..."
 eval "cleanup_added_sources_ ${verbose}"
@@ -266,10 +212,12 @@ else
   done
 fi
 spinner_end
+(( ${#added_sources[@]} > 0 )) && printf "${GREEN}Added sources: %s${RESET}\n" "${added_sources[@]}"
 
 spinner_begin "Updating repositories..."
 eval "update_ ${verbose}" || true
 spinner_end
+(( ${#updated_repositories[@]} > 0 )) && printf "${GREEN}Updated repositories: %s${RESET}\n" "${updated_repositories[@]}"
 
 spinner_begin "Installing..."
 if ${explicit}; then
@@ -288,6 +236,7 @@ else
   done
 fi
 spinner_end
+(( ${#installed_packages[@]} > 0 )) && printf "${GREEN}Installed packages: %s${RESET}\n" "${installed_packages[@]}"
 
 if ! ${explicit}; then
   spinner_begin "wgetting..."
@@ -310,9 +259,11 @@ if ! ${explicit}; then
       fi
       rm "${file}"
     fi
+    wgot_packages+=("${wget}")
   done
   spinner_end
 fi
+(( ${#wgot_packages[@]} > 0 )) && printf "${GREEN}wgot packages: %s${RESET}\n" "${wgot_packages[@]}"
 
 spinner_begin "Purging..."
 if ${explicit}; then
@@ -331,14 +282,7 @@ else
   done
 fi
 spinner_end
-
-if ! ${explicit}; then
-spinner_begin "Running custom commands..."
-for cmd in "${commands[@]}"; do
-    eval "${cmd} ${verbose}"
-  done
-spinner_end
-fi
+(( ${#purged_packages[@]} > 0 )) && printf "${GREEN}Purged packages: %s${RESET}\n" "${purged_packages[@]}"
 
 spinner_begin "Upgrading..."
 if ${explicit}; then
@@ -350,6 +294,14 @@ else
 fi
 spinner_end
 
+if ! ${explicit}; then
+spinner_begin "Running custom commands..."
+for cmd in "${commands[@]}"; do
+    eval "${cmd} ${verbose}"
+  done
+spinner_end
+fi
+
 spinner_begin "Removing unused packages..."
 eval "autoremove_ ${verbose}"
 spinner_end
@@ -359,4 +311,3 @@ eval "upgrade_os_ ${verbose}" || true
 spinner_end
 
 eval "cleanup_added_sources_ ${verbose}"
-
diff --git a/install_with_sudo b/install_with_sudo
--- a/install_with_sudo
+++ b/install_with_sudo
@@ -3,60 +3,34 @@
 # Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
 # Licensed under the MIT License
 
-# Fail script if any command fails.
-set -eu
-
-# Print usage function.
-printUsage() {
-printf "\
-Usage: $(basename "${0}") [options]
-Options:
-  [-d|--debug]
-  [-h|--help]
-"
-}
-
-# Traps
-# shellcheck disable=SC2154
-trap 'return_code=${?}; trap - EXIT; echo EXIT ${return_code}' EXIT
-trap 'return_code=${?}; trap - EXIT; echo HUP ${return_code}' HUP
-trap 'return_code=${?}; trap - EXIT; echo INT ${return_code}' INT
-trap 'return_code=${?}; trap - EXIT; echo QUIT ${return_code}' QUIT
-trap 'return_code=${?}; trap - EXIT; echo PIPE ${return_code}' PIPE
-trap 'return_code=${?}; trap - EXIT; echo TERM ${return_code}' TERM
-trap 'trap - EXIT; echo QUIT' QUIT
-
 # Get script path and append it to PATH so other scripts are callable.
-script_path="$(dirname "${0}")"
-PATH="${PATH}:${script_path}"
+SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
+PATH="${PATH}:${SCRIPT_PATH}"
+
+# Header
+ARGUMENTS="\
+"
+. "${SCRIPT_PATH}/share/header"
 
 # Parse arguments.
-while [[ ${#} -ge 1 ]]; do
-  # Debug mode
-  if [[ "${1}" == "-d" || "${1}" == "--debug" ]]; then
-    shift
-    set -x
-    continue
-  fi
-  # Help: display usage
-  if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
-    shift
-    printUsage
-    exit 0
-  fi
-  # Unrecognized argument.
-  printf "\e[1m\e[31mERROR: Unrecognized argument %s.\e[0m\e[0m\n" "${1}" >&2
-  printUsage
-  exit 1
+while (( ${#} > 0 )); do
+  case "${1}" in
+  *)
+    # Unrecognized argument
+    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; printUsage; exit 1;;
+  esac; shift
 done
 
-pushd ${script_path} > /dev/null
+#------------------------------------------------------------------------------#
+
+pushd "${SCRIPT_PATH}" 1> /dev/null
 {
   mkdir -p /usr/local/bin
   install bin/* /usr/local/bin
   mkdir -p /usr/local/share/curate-pkg/samples
   mkdir -p /usr/local/share/curate-pkg/package-managers
-  install share/spinner.sh /usr/local/share/curate-pkg
+  install share/header /usr/local/share/curate-pkg
+  install share/spinner /usr/local/share/curate-pkg
   install share/*.yaml /usr/local/share/curate-pkg
   install share/package-managers/*.sh /usr/local/share/curate-pkg/package-managers
   install share/samples/* /usr/local/share/curate-pkg/samples
@@ -64,5 +38,4 @@ pushd ${script_path} > /dev/null
     pip install share/yq-2.3.4-py2.py3-none-any.whl
   fi
 }
-popd > /dev/null
-
+popd 1> /dev/null
